POST http://localhost:9101/api/v1/events/
Content-Type: application/json

{
"name":"test-event-2",
"date":"2022-05-25",
"start_time":"10:00:00",
"end_time":"23:59:59",
"multiplier":2,
"description":"test event from postman"
}

###

GET http://localhost:9101/api/v1/events/

###

GET http://localhost:9101/api/v1/events/test-event-1

###

PUT http://localhost:9101/api/v1/events/test-event-1
Content-Type: application/json

{
  "name":"test-event-1",
  "date":"2022-05-25",
  "start_time":"10:00:00",
  "end_time":"23:59:59",
  "multiplier":2,
  "description":"test event from postman"
}

###

DELETE http://localhost:9101/api/v1/events/test-event-1

###

GET http://localhost:9101/api/v1/events/current

###

GET http://localhost:9101/status

###

GET http://localhost:9101/metrics


###
