{{/*apiVersion: prescaling.bedrock.tech/v1*/}}
{{/*kind: PrescalingEvent*/}}
{{/*metadata:*/}}
{{/*  name: test-event*/}}
{{/*spec:*/}}
{{/*  date: "01:01:2022"*/}}
{{/*  start_time: "10:00:00"*/}}
{{/*  end_time: "23:59:59"*/}}
{{/*  multiplier: 2*/}}
{{/*  description: "test event"*/}}
