{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prescaling-exporter.fullname" . }}
  labels:
    {{- include "prescaling-exporter.labels" . | nindent 4 }}
rules:
  # read hpa
  - verbs:
      - get
      - list
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  # CRUD prescaling events
  - verbs:
      - get
      - list
      - create
      - delete
      - update
    apiGroups:
      - prescaling.bedrock.tech
    resources:
      - prescalingevents
{{- end }}
