apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prescaling-exporter.fullname" . }}
  labels:
    {{- include "prescaling-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prescaling-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prescaling-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prescaling-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: metrics
          readinessProbe:
            httpGet:
              path: /status
              port: metrics
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: TZ
              value: {{ .Values.env.timezone | quote }}
            - name: ANNOTATION_START_TIME
              value: {{ .Values.env.annotationStartTime | quote }}
            - name: ANNOTATION_END_TIME
              value: {{ .Values.env.annotationEndTime | quote }}
            - name: ANNOTATION_MIN_REPLICAS
              value: {{ .Values.env.annotationMinReplicas | quote }}
            - name: LABEL_PROJECT
              value: {{ .Values.env.labelProject | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /ko-app/prescaling-exporter
            - serv
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
