name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
        env:
          KO_DOCKER_REPO:  bedrockstreaming/prescaling-exporter
          auth_token: ${{ secrets.DOCKER_AUTH_TOKEN }} 
      - run: |
          echo "${auth_token}" | ko login https://my.registry --username my-username --password-stdin
          ko publish ./
