name: Go Test

on:
  pull_request:
    paths:
      - .github/workflows/go-test.yml
      - pkg/**
      - cmd/**
      - docs/**
      - generated/**
      - go.mod
      - go.sum
      - main.go

jobs:
  linting:
    name: Go lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=30m

  test:
    name: Go test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install
      run: go mod download -x

    - name: Test
      run: go test -v ./...

