name: Go Test

on:
  pull_request:
    paths:
      - .github/workflows/go-test.yml
      - cmd/**
      - docs/**
      - generated/**
      - go.mod
      - go.sum
      - main.go

jobs:
  linting:
    name: Go lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '>=1.18.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3

  test:
    name: Go test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '>=1.18.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install
      run: go install

    - name: Test
      run: go test -v ./...

