name: Helm Lint

on:
  pull_request:
    paths:
      - helm/**

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm3 lint
        run : helm lint ./helm/prescaling-exporter

      - name: Helm3 template
        run : helm template prescaling-exporter helm/prescaling-exporter
