name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bump version on merging Pull Requests with specific labels
        id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1

      - name: Update corresponding major and minor tag
        uses: haya14busa/action-update-semver@v1
        if: "!steps.bumpr.outputs.skip"
        with:
          tag: ${{ steps.bumpr.outputs.next_version }}

      - name: Get tag name
        id: tag
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      - name: Create release
        uses: shogo82148/actions-create-release@v1
        if: "steps.tag.outputs.value != ''"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.value }}
          release_name: Release ${{ steps.tag.outputs.value }}
          body: ${{ steps.bumpr.outputs.message }}
          draft: false
          prerelease: false

      - uses: actions/setup-go@v3
        if: "steps.tag.outputs.value != ''"
        with:
          go-version: '>=1.18.0'

      - id: docker_tag
        run: echo "::set-output name=tag::$(echo ${{steps.tag.outputs.value}} | cut -c 2-)"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: "steps.tag.outputs.value != ''"
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - uses: imjasonh/setup-ko@v0.4

      - name: Build and Push on Docker Hub  
        if: "steps.tag.outputs.value != ''"
        env:
          KO_DOCKER_REPO: bedrockstreaming/prescaling-exporter
        run: ko publish . --bare --tags latest,${{steps.docker_tag.outputs.tag}}

  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
